---
- name: Generate the WireGuard private and public keys
  shell: |
    umask 077
    wg genkey | tee privatekey | wg pubkey > publickey
  args:
    chdir: /etc/wireguard
    creates: /etc/wireguard/publickey

- name: Get the WireGuard private key
  command: "cat /etc/wireguard/privatekey"
  register: wireguard_private_key

- name: Generate server configuration from template for {{ WIREGUARD_INTERFACE }} interface
  template:
    src: templates/wg-server.j2
    dest: /etc/wireguard/{{ WIREGUARD_INTERFACE }}.conf
    mode: 0600
